include Makefile.inc
include components

#INSTALLDIR = ~/public_html
INSTALLDIR = /var/www/html

NET_O-$(CONFIG_NET) += net.o

OBJS = \
	arch.o \
	kernel.o \
	lib.o \
	dev.o \
	$(NET_O-y) \
	user.o

all: config.h ertos

config.h: config.h.in components
	echo "/* This file is autogenerated. Edit config.h.in instead. */" > config.h
	echo >> config.h
	echo "#ifndef _CONFIG_H" >> config.h
	echo "#define _CONFIG_H" >> config.h
	echo >> config.h
	echo "/* From config.h.in */" >> config.h
	cat config.h.in >> config.h
	echo >> config.h
	echo "/* From components */" >> config.h
	sed 's/^\(.*\)=.*/#define \1/' components >> config.h
	echo >> config.h
	echo "#endif" >> config.h
	

ertos: $(OBJS)
	$(LD) -Map=ertos.map -T ertos.ld -o ertos.elf $(OBJS)
	$(OBJCOPY) -O binary ertos.elf ertos.bin
	ls -lh ertos.elf ertos.bin

arch.o: force_look
	$(MAKE) -C arch

kernel.o: force_look
	$(MAKE) -C kernel

lib.o: force_look
	$(MAKE) -C lib

dev.o: force_look
	$(MAKE) -C dev

net.o: force_look
	$(MAKE) -C net

user.o: force_look
	$(MAKE) -C user

force_look:
	true

install:
	cp ertos.elf $(INSTALLDIR)
	cp ertos.bin $(INSTALLDIR)

clean:
	rm -f *.o ertos.elf ertos.bin ertos.map
	for dir in $(OBJS); do \
		$(MAKE) -C `basename $$dir .o` clean; \
	done

